### ISSUE TITLE
Reload data method.

### ISSUE THREAD

**Issue by daliadanila** [tipsi/tipsi-dropdown-ios#8]
Hi,

Would it be possible to have a method to reload the dropdown picker? Something similar to tableView's reloadData method. So that when the datasource changes, to call it and to update dropdown's options.

Otherwise, very simple and easy to use control. Thanks!

**Comment by daliadanila** [comment]
Just realised it will update the options when reassigning to items.

 dropdown.items = @[@"Orange"] does the tricks.

**Comment by dmytrozavgorodniy** [comment]
Yes, we designed TPSDropDown like UISegmentedControl component from UIKit. You right, you can reload items when you reset it. If you still have any questions, please, give us know. Thanks
